---
:api_key: afc0db74bbd4d0d0ad09e2733e8952a1
:password: 53f8e1d46c51e9c1987e55d8fc59e70f
:theme_id: '3'
:preview_url: https://trembaodistribuidorademineirices.commercesuite.com.br/loja/loja.php?loja=653859&opencode_theme=5b8c95c8ab712
